import type { Affirmation, AwarenessPrompt } from '@/lib/types';

export const affirmations: Affirmation[] = [
  { id: 'a1', text: 'I absorb languages like a sponge — every word is wiring new neural pathways in my mind right now.', category: 'language' },
  { id: 'a2', text: 'My brain is a pattern-recognition machine. I am built to learn languages fast.', category: 'language' },
  { id: 'a3', text: 'Every moment I engage with Russian, I am becoming the person who speaks Russian fluently.', category: 'language' },
  { id: 'a4', text: 'I learn from every mistake. Each error is a teacher, not a verdict.', category: 'growth' },
  { id: 'a5', text: 'I show up consistently. Small daily actions compound into extraordinary results.', category: 'consistency' },
  { id: 'a6', text: 'I have the discipline of a world-class athlete applied to language learning.', category: 'consistency' },
  { id: 'a7', text: 'My memory is sharp. My recall is deepening with every review session.', category: 'language' },
  { id: 'a8', text: 'I am not just learning a language — I am expanding my consciousness into a new world.', category: 'growth' },
  { id: 'a9', text: 'Confidence in Russian comes through practice, not perfection. I embrace the messy middle.', category: 'confidence' },
  { id: 'a10', text: "I speak even when it's imperfect. Communication is the goal, not flawlessness.", category: 'confidence' },
  { id: 'a11', text: 'I am the kind of person who finishes what they start. I will reach fluency.', category: 'consistency' },
  { id: 'a12', text: 'Native speakers are rooting for me. My effort to learn their language is an act of respect.', category: 'confidence' },
  { id: 'a13', text: 'I understand more Russian today than I did yesterday. Forward is the only direction.', category: 'growth' },
  { id: 'a14', text: "My subconscious is processing Russian even when I'm not consciously studying. I grow 24/7.", category: 'language' },
  { id: 'a15', text: 'I am fully present during every study session. My focus is legendary.', category: 'consistency' },
  { id: 'a16', text: 'I have a gift for making connections — I link new words to vivid stories effortlessly.', category: 'language' },
  { id: 'a17', text: 'The discomfort of not knowing is temporary. Fluency is permanent.', category: 'growth' },
  { id: 'a18', text: 'I am building a skill that will serve me for the rest of my life. This is worth every minute.', category: 'growth' },
  { id: 'a19', text: 'I love the sound of Russian. I am tuning my ear to its rhythm every single day.', category: 'language' },
  { id: 'a20', text: 'My inner self is vast and limitless. Learning expands the frontier of who I am.', category: 'growth' },
  { id: 'a21', text: 'I trust my process. Neomonix is working. My mnemonic stories stick.', category: 'confidence' },
  { id: 'a22', text: 'I am grateful for every word I know. Gratitude accelerates learning.', category: 'growth' },
  { id: 'a23', text: 'When I shadow native speakers, I am borrowing their fluency and making it my own.', category: 'language' },
  { id: 'a24', text: "I do not compare my chapter one to someone else's chapter twenty. My journey is mine.", category: 'confidence' },
  { id: 'a25', text: 'Every phrase I master opens a new door to human connection.', category: 'language' },
  { id: 'a26', text: 'I am mentally strong. I push through plateaus with curiosity, not frustration.', category: 'consistency' },
  { id: 'a27', text: 'My awareness grows alongside my vocabulary. Language is consciousness expansion.', category: 'growth' },
  { id: 'a28', text: 'I am a polyglot in the making. Russian is just the beginning.', category: 'confidence' },
  { id: 'a29', text: 'I give myself full permission to be a beginner and still feel powerful.', category: 'confidence' },
  { id: 'a30', text: 'I am awake. I am aware. I am building something extraordinary, one word at a time.', category: 'growth' },
];

export const awarenessPrompts: AwarenessPrompt[] = [
  { id: 'p1', question: 'What is one Russian word or phrase you heard or used today that surprised you?', hint: 'Notice what caught your attention — your brain is already making connections.' },
  { id: 'p2', question: 'When do you feel most alive and in flow while learning? What does that state feel like?', hint: 'Understanding your peak learning state helps you recreate it intentionally.' },
  { id: 'p3', question: 'What would change in your life if you were fluent in Russian tomorrow?', hint: 'Let yourself dream fully. Specificity creates motivation.' },
  { id: 'p4', question: 'What limiting belief about language learning are you ready to release today?', hint: "'I'm not good at languages' — is that true, or just a story?" },
  { id: 'p5', question: 'Which aspect of Russian culture draws you in the most, and why?', hint: "Connection to culture is connection to the language's soul." },
  { id: 'p6', question: 'If you could have a conversation with any Russian-speaking person, living or historical, who would it be and what would you ask?', hint: 'This reveals what truly matters to you about the language.' },
  { id: 'p7', question: 'What did you find difficult today, and how does overcoming difficulty make you stronger?', hint: 'Reframe struggle as training, not failure.' },
  { id: 'p8', question: 'How is learning Russian changing the way you think or see the world?', hint: "Languages don't just describe reality — they shape how you perceive it." },
  { id: 'p9', question: "What small win can you celebrate from today's learning session?", hint: 'Recognizing progress, however small, compounds motivation.' },
  { id: 'p10', question: 'What is the gap between who you are today and who you need to be to speak Russian fluently?', hint: 'Identify the gap clearly so you can close it with intention.' },
  { id: 'p11', question: 'How does your body feel when you learn something new? Where do you feel curiosity physically?', hint: 'Learning is embodied — your body knows things before your mind does.' },
  { id: 'p12', question: "What pattern did you notice in today's vocabulary that you hadn't seen before?", hint: 'Patterns are the architecture of language — finding them is genius.' },
  { id: 'p13', question: 'Who in your life would most benefit from you learning Russian, and how?', hint: 'Purpose beyond yourself amplifies commitment.' },
  { id: 'p14', question: 'If learning Russian is a metaphor for your life — what is it teaching you about yourself?', hint: 'Every skill you develop is also self-development in disguise.' },
  { id: 'p15', question: 'What does consistency mean to you, and how are you embodying it right now?', hint: 'Showing up daily IS the transformation, not just a means to it.' },
  { id: 'p16', question: 'What is one Russian sentence you want to be able to say by the end of this month?', hint: 'Specificity creates a north star for your practice.' },
  { id: 'p17', question: 'How do you handle the frustration of plateaus, and what gets you through them?', hint: 'Plateaus are consolidation phases. Your brain is organizing, not stalling.' },
  { id: 'p18', question: "What does your inner monologue sound like when you're studying? Is it supportive?", hint: 'The voice inside is either your greatest coach or your worst critic.' },
  { id: 'p19', question: "If Russian words were colors, what color would today's lesson be?", hint: 'Creative metaphors anchor abstract learning in felt experience.' },
  { id: 'p20', question: 'What is one thing you would tell your past self about learning languages?', hint: "The wisdom you'd give your past self is advice you need now too." },
  { id: 'p21', question: 'How does expanding your language also expand your identity?', hint: 'Every new language gives you a new way of being in the world.' },
  { id: 'p22', question: 'What does "mastery" mean to you in the context of Russian?', hint: 'Your definition of mastery shapes what you practice and how long you persist.' },
  { id: 'p23', question: 'What are you most grateful for about your ability to learn?', hint: 'Gratitude for capacity multiplies that very capacity.' },
  { id: 'p24', question: 'Where do you feel resistance in your learning practice, and what is that resistance protecting?', hint: 'Resistance always points to something worth exploring.' },
  { id: 'p25', question: 'If fluency in Russian is inevitable — what changes about how you approach today\'s session?', hint: 'Operating from certainty of outcome transforms the quality of present effort.' },
  { id: 'p26', question: 'What Russian phrase feels most alive in your mouth right now?', hint: 'The words that resonate are the ones your brain will remember longest.' },
  { id: 'p27', question: 'How would you describe your relationship with discomfort and uncertainty in learning?', hint: "Comfort with not-knowing is the master learner's greatest superpower." },
  { id: 'p28', question: 'What would it mean for your life if language barriers simply ceased to exist for you?', hint: 'Vision so compelling it pulls you forward automatically.' },
  { id: 'p29', question: 'What is one action you took today that your future fluent self will thank you for?', hint: 'Your actions today ARE the future version of you being built.' },
  { id: 'p30', question: "If you could describe your language-learning journey as a hero's quest — where are you on the map right now?", hint: 'You are the hero. Every chapter has challenges. Which one are you in?' },
];
