import type { Phrase } from '@/lib/types';

type SeedPhrase = Omit<Phrase, 'id' | 'drillStatus' | 'createdAt'>;

export const russianPhrases: SeedPhrase[] = [
  // ─── GREETINGS ───
  { languageCode: 'ru', original: 'Привет', romanization: 'Privyet', translation: 'Hi / Hello (informal)', category: 'greetings', isCustom: false },
  { languageCode: 'ru', original: 'Здравствуйте', romanization: 'Zdravstvuyte', translation: 'Hello (formal)', category: 'greetings', isCustom: false },
  { languageCode: 'ru', original: 'Доброе утро', romanization: 'Dobroye utro', translation: 'Good morning', category: 'greetings', isCustom: false },
  { languageCode: 'ru', original: 'Добрый день', romanization: "Dobry dyen'", translation: 'Good afternoon', category: 'greetings', isCustom: false },
  { languageCode: 'ru', original: 'Добрый вечер', romanization: 'Dobry vecher', translation: 'Good evening', category: 'greetings', isCustom: false },
  { languageCode: 'ru', original: 'Как дела?', romanization: 'Kak dela?', translation: 'How are you?', category: 'greetings', isCustom: false },
  { languageCode: 'ru', original: 'Как ты?', romanization: 'Kak ty?', translation: 'How are you? (informal)', category: 'greetings', isCustom: false },
  { languageCode: 'ru', original: 'Как поживаешь?', romanization: 'Kak pozhivayesh?', translation: 'How are you doing?', category: 'greetings', isCustom: false },
  { languageCode: 'ru', original: 'Хорошо, спасибо', romanization: 'Kharasho, spasiba', translation: 'Fine, thank you', category: 'greetings', isCustom: false },
  { languageCode: 'ru', original: 'Нормально', romanization: "Normal'na", translation: 'Okay / Normal', category: 'greetings', isCustom: false },
  { languageCode: 'ru', original: 'Всё хорошо', romanization: 'Vsyo kharasho', translation: 'Everything is fine', category: 'greetings', isCustom: false },
  { languageCode: 'ru', original: 'Рад тебя видеть', romanization: "Rat tebya videt'", translation: 'Glad to see you', category: 'greetings', isCustom: false },
  { languageCode: 'ru', original: 'Очень приятно', romanization: "Ochen' priyatna", translation: 'Very nice to meet you', category: 'greetings', isCustom: false },
  { languageCode: 'ru', original: 'Рад познакомиться', romanization: 'Rat paznakomitsa', translation: 'Glad to meet you', category: 'greetings', isCustom: false },
  { languageCode: 'ru', original: 'Как вас зовут?', romanization: 'Kak vas zavut?', translation: 'What is your name? (formal)', category: 'greetings', isCustom: false },
  { languageCode: 'ru', original: 'Как тебя зовут?', romanization: 'Kak tebya zavut?', translation: 'What is your name? (informal)', category: 'greetings', isCustom: false },
  { languageCode: 'ru', original: 'Меня зовут...', romanization: 'Menya zavut...', translation: 'My name is...', category: 'greetings', isCustom: false },
  { languageCode: 'ru', original: 'Давно не виделись', romanization: "Davno ne videlis'", translation: 'Long time no see', category: 'greetings', isCustom: false },

  // ─── FAREWELLS ───
  { languageCode: 'ru', original: 'До свидания', romanization: 'Do svidaniya', translation: 'Goodbye (formal)', category: 'farewells', isCustom: false },
  { languageCode: 'ru', original: 'Пока', romanization: 'Paka', translation: 'Bye (informal)', category: 'farewells', isCustom: false },
  { languageCode: 'ru', original: 'До встречи', romanization: 'Do vstrechi', translation: 'See you later', category: 'farewells', isCustom: false },
  { languageCode: 'ru', original: 'До завтра', romanization: 'Do zavtra', translation: 'See you tomorrow', category: 'farewells', isCustom: false },
  { languageCode: 'ru', original: 'Спокойной ночи', romanization: 'Spokoinoy nochi', translation: 'Good night', category: 'farewells', isCustom: false },
  { languageCode: 'ru', original: 'Удачи!', romanization: 'Udachi!', translation: 'Good luck!', category: 'farewells', isCustom: false },
  { languageCode: 'ru', original: 'Всего доброго', romanization: 'Vsevo dobrova', translation: 'All the best', category: 'farewells', isCustom: false },
  { languageCode: 'ru', original: 'Увидимся', romanization: 'Uvidimsya', translation: 'See you', category: 'farewells', isCustom: false },
  { languageCode: 'ru', original: 'Счастливо', romanization: 'Schastlivo', translation: 'Have a good one / Farewell', category: 'farewells', isCustom: false },
  { languageCode: 'ru', original: 'Береги себя', romanization: 'Beregi sebya', translation: 'Take care of yourself', category: 'farewells', isCustom: false },

  // ─── POLITENESS ───
  { languageCode: 'ru', original: 'Спасибо', romanization: 'Spasiba', translation: 'Thank you', category: 'politeness', isCustom: false },
  { languageCode: 'ru', original: 'Большое спасибо', romanization: "Bol'shoye spasiba", translation: 'Thank you very much', category: 'politeness', isCustom: false },
  { languageCode: 'ru', original: 'Пожалуйста', romanization: 'Pazhalsta', translation: "Please / You're welcome", category: 'politeness', isCustom: false },
  { languageCode: 'ru', original: 'Не за что', romanization: 'Nye za shto', translation: "Don't mention it / No problem", category: 'politeness', isCustom: false },
  { languageCode: 'ru', original: 'Извините', romanization: 'Izvinite', translation: "Excuse me / I'm sorry (formal)", category: 'politeness', isCustom: false },
  { languageCode: 'ru', original: 'Прости', romanization: 'Prosti', translation: 'Sorry (informal)', category: 'politeness', isCustom: false },
  { languageCode: 'ru', original: 'Ничего страшного', romanization: 'Nichevo strashnova', translation: "No worries / It's nothing", category: 'politeness', isCustom: false },
  { languageCode: 'ru', original: 'Будьте добры', romanization: "Bud'te dobry", translation: 'Be so kind / Would you please', category: 'politeness', isCustom: false },
  { languageCode: 'ru', original: 'С удовольствием', romanization: "S udovol'stviyem", translation: 'With pleasure', category: 'politeness', isCustom: false },
  { languageCode: 'ru', original: 'Конечно', romanization: 'Konyeshno', translation: 'Of course', category: 'politeness', isCustom: false },

  // ─── QUESTIONS ───
  { languageCode: 'ru', original: 'Что это?', romanization: 'Shto eta?', translation: 'What is this?', category: 'questions', isCustom: false },
  { languageCode: 'ru', original: 'Где это?', romanization: 'Gdye eta?', translation: 'Where is this?', category: 'questions', isCustom: false },
  { languageCode: 'ru', original: 'Когда?', romanization: 'Kagda?', translation: 'When?', category: 'questions', isCustom: false },
  { languageCode: 'ru', original: 'Почему?', romanization: 'Pachemu?', translation: 'Why?', category: 'questions', isCustom: false },
  { languageCode: 'ru', original: 'Как это?', romanization: 'Kak eta?', translation: 'How so? / How is this?', category: 'questions', isCustom: false },
  { languageCode: 'ru', original: 'Сколько стоит?', romanization: "Skol'ka stoit?", translation: 'How much does it cost?', category: 'questions', isCustom: false },
  { languageCode: 'ru', original: 'Вы говорите по-английски?', romanization: 'Vy gavarite pa-angliyski?', translation: 'Do you speak English?', category: 'questions', isCustom: false },
  { languageCode: 'ru', original: 'Вы говорите по-русски?', romanization: 'Vy gavarite pa-russki?', translation: 'Do you speak Russian?', category: 'questions', isCustom: false },
  { languageCode: 'ru', original: 'Что это значит?', romanization: 'Shto eta znachit?', translation: 'What does this mean?', category: 'questions', isCustom: false },
  { languageCode: 'ru', original: 'Как это сказать по-русски?', romanization: "Kak eta skazat' pa-russki?", translation: 'How do you say this in Russian?', category: 'questions', isCustom: false },
  { languageCode: 'ru', original: 'Повторите, пожалуйста', romanization: 'Paftarite, pazhalsta', translation: 'Please repeat that', category: 'questions', isCustom: false },
  { languageCode: 'ru', original: 'Говорите медленнее', romanization: 'Gavarite medlenneyе', translation: 'Speak more slowly', category: 'questions', isCustom: false },
  { languageCode: 'ru', original: 'Я не понимаю', romanization: 'Ya nye panimayu', translation: "I don't understand", category: 'questions', isCustom: false },
  { languageCode: 'ru', original: 'Можете объяснить?', romanization: "Mozhete ob'yasnit'?", translation: 'Can you explain?', category: 'questions', isCustom: false },
  { languageCode: 'ru', original: 'Откуда вы?', romanization: 'Otkuda vy?', translation: 'Where are you from?', category: 'questions', isCustom: false },

  // ─── DIRECTIONS ───
  { languageCode: 'ru', original: 'Где находится...?', romanization: 'Gdye nakhoditsa...?', translation: 'Where is...?', category: 'directions', isCustom: false },
  { languageCode: 'ru', original: 'Как пройти к...?', romanization: 'Kak proyti k...?', translation: 'How do I get to...?', category: 'directions', isCustom: false },
  { languageCode: 'ru', original: 'Налево', romanization: 'Naleva', translation: 'To the left', category: 'directions', isCustom: false },
  { languageCode: 'ru', original: 'Направо', romanization: 'Naprava', translation: 'To the right', category: 'directions', isCustom: false },
  { languageCode: 'ru', original: 'Прямо', romanization: 'Pryamo', translation: 'Straight ahead', category: 'directions', isCustom: false },
  { languageCode: 'ru', original: 'Далеко отсюда?', romanization: 'Daleko otsyuda?', translation: 'Is it far from here?', category: 'directions', isCustom: false },
  { languageCode: 'ru', original: 'Я заблудился', romanization: 'Ya zabloodilsya', translation: 'I am lost (male)', category: 'directions', isCustom: false },
  { languageCode: 'ru', original: 'Я заблудилась', romanization: "Ya zabloodelas'", translation: 'I am lost (female)', category: 'directions', isCustom: false },
  { languageCode: 'ru', original: 'На следующем перекрёстке', romanization: 'Na sleduyushchem perekryostke', translation: 'At the next intersection', category: 'directions', isCustom: false },
  { languageCode: 'ru', original: 'Рядом с...', romanization: 'Ryadam s...', translation: 'Next to...', category: 'directions', isCustom: false },
  { languageCode: 'ru', original: 'Напротив', romanization: 'Naprotiv', translation: 'Across from / Opposite', category: 'directions', isCustom: false },
  { languageCode: 'ru', original: 'Остановка автобуса', romanization: 'Astanovka avtobusa', translation: 'Bus stop', category: 'directions', isCustom: false },
  { languageCode: 'ru', original: 'Станция метро', romanization: 'Stantsiya metro', translation: 'Metro station', category: 'directions', isCustom: false },

  // ─── TRAVEL ───
  { languageCode: 'ru', original: 'Один билет, пожалуйста', romanization: 'Odin bilet, pazhalsta', translation: 'One ticket, please', category: 'travel', isCustom: false },
  { languageCode: 'ru', original: 'Где аэропорт?', romanization: 'Gdye aeroport?', translation: 'Where is the airport?', category: 'travel', isCustom: false },
  { languageCode: 'ru', original: 'Где вокзал?', romanization: 'Gdye vagzal?', translation: 'Where is the train station?', category: 'travel', isCustom: false },
  { languageCode: 'ru', original: 'Мне нужно такси', romanization: 'Mnye nuzhna taksi', translation: 'I need a taxi', category: 'travel', isCustom: false },
  { languageCode: 'ru', original: 'Сколько до центра?', romanization: "Skol'ka do tsentra?", translation: 'How much to the center?', category: 'travel', isCustom: false },
  { languageCode: 'ru', original: 'Когда отправляется поезд?', romanization: 'Kagda atpravlyaetsa poyezd?', translation: 'When does the train depart?', category: 'travel', isCustom: false },
  { languageCode: 'ru', original: 'Где мой отель?', romanization: "Gdye moy otel'?", translation: 'Where is my hotel?', category: 'travel', isCustom: false },
  { languageCode: 'ru', original: 'Есть ли свободные номера?', romanization: "Yest' li svobodnyye nomera?", translation: 'Are there any available rooms?', category: 'travel', isCustom: false },
  { languageCode: 'ru', original: 'Во сколько выезд?', romanization: "Va skol'ka vyezd?", translation: 'What time is checkout?', category: 'travel', isCustom: false },
  { languageCode: 'ru', original: 'Мой багаж потерялся', romanization: 'Moy bagazh pateryalsya', translation: 'My luggage is lost', category: 'travel', isCustom: false },
  { languageCode: 'ru', original: 'У меня бронь', romanization: "U menya bron'", translation: 'I have a reservation', category: 'travel', isCustom: false },
  { languageCode: 'ru', original: 'Паспортный контроль', romanization: "Pasportny kontrol'", translation: 'Passport control', category: 'travel', isCustom: false },

  // ─── FOOD ───
  { languageCode: 'ru', original: 'Я хочу заказать', romanization: "Ya khachu zakazat'", translation: 'I would like to order', category: 'food', isCustom: false },
  { languageCode: 'ru', original: 'Счёт, пожалуйста', romanization: 'Shchot, pazhalsta', translation: 'The bill, please', category: 'food', isCustom: false },
  { languageCode: 'ru', original: 'Что вы рекомендуете?', romanization: 'Shto vy rekamenduyete?', translation: 'What do you recommend?', category: 'food', isCustom: false },
  { languageCode: 'ru', original: 'Я вегетарианец', romanization: 'Ya vegetarianets', translation: 'I am a vegetarian (male)', category: 'food', isCustom: false },
  { languageCode: 'ru', original: 'Без мяса, пожалуйста', romanization: 'Byez myasa, pazhalsta', translation: 'Without meat, please', category: 'food', isCustom: false },
  { languageCode: 'ru', original: 'Это очень вкусно', romanization: "Eta ochen' vkusna", translation: 'This is very delicious', category: 'food', isCustom: false },
  { languageCode: 'ru', original: 'Дайте воды, пожалуйста', romanization: 'Dayte vody, pazhalsta', translation: 'Give me water, please', category: 'food', isCustom: false },
  { languageCode: 'ru', original: 'Кофе с молоком', romanization: 'Kofe s molokom', translation: 'Coffee with milk', category: 'food', isCustom: false },
  { languageCode: 'ru', original: 'Я хочу есть', romanization: "Ya khachu yest'", translation: 'I want to eat', category: 'food', isCustom: false },
  { languageCode: 'ru', original: 'Приятного аппетита', romanization: 'Priyatnava appetita', translation: 'Enjoy your meal / Bon appétit', category: 'food', isCustom: false },
  { languageCode: 'ru', original: 'У вас есть меню?', romanization: "U vas yest' menyu?", translation: 'Do you have a menu?', category: 'food', isCustom: false },
  { languageCode: 'ru', original: 'Я голоден', romanization: 'Ya goloden', translation: 'I am hungry (male)', category: 'food', isCustom: false },

  // ─── SHOPPING ───
  { languageCode: 'ru', original: 'Сколько это стоит?', romanization: "Skol'ka eta stoit?", translation: 'How much does this cost?', category: 'shopping', isCustom: false },
  { languageCode: 'ru', original: 'Это слишком дорого', romanization: 'Eta slishkam dorogo', translation: 'This is too expensive', category: 'shopping', isCustom: false },
  { languageCode: 'ru', original: 'Есть ли скидка?', romanization: "Yest' li skidka?", translation: 'Is there a discount?', category: 'shopping', isCustom: false },
  { languageCode: 'ru', original: 'Можно примерить?', romanization: "Mozhna primerit'?", translation: 'Can I try it on?', category: 'shopping', isCustom: false },
  { languageCode: 'ru', original: 'Какой размер?', romanization: 'Kakoy razmer?', translation: 'What size?', category: 'shopping', isCustom: false },
  { languageCode: 'ru', original: 'У вас есть другой цвет?', romanization: "U vas yest' drugoy tsvet?", translation: 'Do you have another color?', category: 'shopping', isCustom: false },
  { languageCode: 'ru', original: 'Я возьму это', romanization: "Ya voz'mu eta", translation: "I'll take this", category: 'shopping', isCustom: false },
  { languageCode: 'ru', original: 'Можно оплатить картой?', romanization: "Mozhna aplatit' kartoy?", translation: 'Can I pay by card?', category: 'shopping', isCustom: false },

  // ─── HEALTH ───
  { languageCode: 'ru', original: 'Мне плохо', romanization: 'Mnye plokha', translation: 'I feel sick / I feel bad', category: 'health', isCustom: false },
  { languageCode: 'ru', original: 'Вызовите врача', romanization: 'Vyzavite vracha', translation: 'Call a doctor', category: 'health', isCustom: false },
  { languageCode: 'ru', original: 'Вызовите скорую помощь', romanization: "Vyzavite skoruyu pomoshch'", translation: 'Call an ambulance', category: 'health', isCustom: false },
  { languageCode: 'ru', original: 'Где аптека?', romanization: 'Gdye apteka?', translation: 'Where is the pharmacy?', category: 'health', isCustom: false },
  { languageCode: 'ru', original: 'У меня болит голова', romanization: 'U menya bolit galava', translation: 'I have a headache', category: 'health', isCustom: false },
  { languageCode: 'ru', original: 'У меня температура', romanization: 'U menya temperatura', translation: 'I have a fever', category: 'health', isCustom: false },
  { languageCode: 'ru', original: 'Мне нужны лекарства', romanization: 'Mnye nuzhny lekarstva', translation: 'I need medicine', category: 'health', isCustom: false },
  { languageCode: 'ru', original: 'Я аллергик на...', romanization: 'Ya allergik na...', translation: 'I am allergic to...', category: 'health', isCustom: false },

  // ─── EMOTIONS ───
  { languageCode: 'ru', original: 'Я рад(а)', romanization: 'Ya rat / rada', translation: 'I am glad / happy (m/f)', category: 'emotions', isCustom: false },
  { languageCode: 'ru', original: 'Мне грустно', romanization: 'Mnye grustna', translation: 'I am sad', category: 'emotions', isCustom: false },
  { languageCode: 'ru', original: 'Я устал(а)', romanization: 'Ya ustal / ustala', translation: 'I am tired (m/f)', category: 'emotions', isCustom: false },
  { languageCode: 'ru', original: 'Я взволнован(а)', romanization: 'Ya vzvolnovan / vzvolnovana', translation: 'I am excited / nervous (m/f)', category: 'emotions', isCustom: false },
  { languageCode: 'ru', original: 'Мне скучно', romanization: 'Mnye skuchna', translation: 'I am bored', category: 'emotions', isCustom: false },
  { languageCode: 'ru', original: 'Я люблю тебя', romanization: 'Ya lyublyu tebya', translation: 'I love you', category: 'emotions', isCustom: false },
  { languageCode: 'ru', original: 'Ты мне нравишься', romanization: 'Ty mnye nravishsya', translation: 'I like you', category: 'emotions', isCustom: false },
  { languageCode: 'ru', original: 'Я горжусь тобой', romanization: "Ya gorzhus' toboy", translation: 'I am proud of you', category: 'emotions', isCustom: false },
  { languageCode: 'ru', original: 'Мне страшно', romanization: 'Mnye strashna', translation: 'I am scared', category: 'emotions', isCustom: false },
  { languageCode: 'ru', original: 'Я злой(злая)', romanization: 'Ya zloy / zlaya', translation: 'I am angry (m/f)', category: 'emotions', isCustom: false },

  // ─── FAMILY ───
  { languageCode: 'ru', original: 'Это моя семья', romanization: "Eta maya sem'ya", translation: 'This is my family', category: 'family', isCustom: false },
  { languageCode: 'ru', original: 'Мой муж', romanization: 'Moy muzh', translation: 'My husband', category: 'family', isCustom: false },
  { languageCode: 'ru', original: 'Моя жена', romanization: 'Maya zhena', translation: 'My wife', category: 'family', isCustom: false },
  { languageCode: 'ru', original: 'Мои дети', romanization: 'Moi deti', translation: 'My children', category: 'family', isCustom: false },
  { languageCode: 'ru', original: 'Мой сын', romanization: 'Moy syn', translation: 'My son', category: 'family', isCustom: false },
  { languageCode: 'ru', original: 'Моя дочь', romanization: "Maya doch'", translation: 'My daughter', category: 'family', isCustom: false },
  { languageCode: 'ru', original: 'Мама и папа', romanization: 'Mama i papa', translation: 'Mom and dad', category: 'family', isCustom: false },
  { languageCode: 'ru', original: 'У тебя есть братья и сёстры?', romanization: "U tebya yest' brat'ya i syostry?", translation: 'Do you have brothers and sisters?', category: 'family', isCustom: false },

  // ─── WORK ───
  { languageCode: 'ru', original: 'Я учу русский язык', romanization: 'Ya uchu russky yazyk', translation: 'I am learning Russian', category: 'work', isCustom: false },
  { languageCode: 'ru', original: 'Где вы работаете?', romanization: 'Gdye vy rabotaete?', translation: 'Where do you work?', category: 'work', isCustom: false },
  { languageCode: 'ru', original: 'Я студент', romanization: 'Ya student', translation: 'I am a student (male)', category: 'work', isCustom: false },
  { languageCode: 'ru', original: 'Я работаю в...', romanization: 'Ya rabotayu v...', translation: 'I work at/in...', category: 'work', isCustom: false },
  { languageCode: 'ru', original: 'Какая у вас профессия?', romanization: 'Kakaya u vas professiya?', translation: 'What is your profession?', category: 'work', isCustom: false },
  { languageCode: 'ru', original: 'Я занят(а) сейчас', romanization: 'Ya zanyat / zanyata seychas', translation: 'I am busy right now (m/f)', category: 'work', isCustom: false },
  { languageCode: 'ru', original: 'У меня встреча', romanization: 'U menya vstrecha', translation: 'I have a meeting', category: 'work', isCustom: false },

  // ─── NUMBERS & TIME ───
  { languageCode: 'ru', original: 'Который час?', romanization: 'Kotory chas?', translation: 'What time is it?', category: 'numbers', isCustom: false },
  { languageCode: 'ru', original: 'Сейчас три часа', romanization: "Seychas tri chasa", translation: "It is three o'clock", category: 'numbers', isCustom: false },
  { languageCode: 'ru', original: 'Один, два, три', romanization: 'Odin, dva, tri', translation: 'One, two, three', category: 'numbers', isCustom: false },
  { languageCode: 'ru', original: 'Четыре, пять, шесть', romanization: "Chetyre, pyat', shest'", translation: 'Four, five, six', category: 'numbers', isCustom: false },
  { languageCode: 'ru', original: 'Семь, восемь, девять, десять', romanization: "Sem', vosem', devyat', desyat'", translation: 'Seven, eight, nine, ten', category: 'numbers', isCustom: false },
  { languageCode: 'ru', original: 'Сто рублей', romanization: 'Sto rubley', translation: 'One hundred rubles', category: 'numbers', isCustom: false },
  { languageCode: 'ru', original: 'Сколько времени?', romanization: "Skol'ka vremeni?", translation: 'What time is it? / How much time?', category: 'numbers', isCustom: false },

  // ─── WEATHER ───
  { languageCode: 'ru', original: 'Какая сегодня погода?', romanization: 'Kakaya sevodnya pagoda?', translation: 'What is the weather like today?', category: 'weather', isCustom: false },
  { languageCode: 'ru', original: 'Идёт дождь', romanization: "Idyot dozhd'", translation: 'It is raining', category: 'weather', isCustom: false },
  { languageCode: 'ru', original: 'Идёт снег', romanization: 'Idyot snyeg', translation: 'It is snowing', category: 'weather', isCustom: false },
  { languageCode: 'ru', original: 'Холодно', romanization: 'Kholadna', translation: 'It is cold', category: 'weather', isCustom: false },
  { languageCode: 'ru', original: 'Жарко', romanization: 'Zharka', translation: 'It is hot', category: 'weather', isCustom: false },
  { languageCode: 'ru', original: 'Сегодня солнечно', romanization: 'Sevodnya solnechna', translation: 'Today it is sunny', category: 'weather', isCustom: false },
  { languageCode: 'ru', original: 'Возьми зонтик', romanization: "Voz'mi zontik", translation: 'Take an umbrella', category: 'weather', isCustom: false },

  // ─── SOCIAL ───
  { languageCode: 'ru', original: 'Давайте выпьем', romanization: "Davayte vip'em", translation: "Let's drink / Cheers", category: 'social', isCustom: false },
  { languageCode: 'ru', original: 'За здоровье!', romanization: "Za zdorov'ye!", translation: 'To health! / Cheers!', category: 'social', isCustom: false },
  { languageCode: 'ru', original: 'Где туалет?', romanization: 'Gdye tualyet?', translation: 'Where is the bathroom?', category: 'social', isCustom: false },
  { languageCode: 'ru', original: 'Помогите!', romanization: 'Pamagite!', translation: 'Help!', category: 'social', isCustom: false },
  { languageCode: 'ru', original: 'Пойдём вместе?', romanization: 'Poydom vmeste?', translation: 'Shall we go together?', category: 'social', isCustom: false },
  { languageCode: 'ru', original: 'Я из Америки', romanization: 'Ya iz Ameriki', translation: 'I am from America', category: 'social', isCustom: false },
  { languageCode: 'ru', original: 'Мне нравится Россия', romanization: 'Mnye nravitsya Rossiya', translation: 'I like Russia', category: 'social', isCustom: false },
  { languageCode: 'ru', original: 'Ты свободен вечером?', romanization: 'Ty svoboden vecherom?', translation: 'Are you free this evening? (male)', category: 'social', isCustom: false },
  { languageCode: 'ru', original: 'Это было здорово', romanization: 'Eta byla zdorovo', translation: 'That was great', category: 'social', isCustom: false },
  { languageCode: 'ru', original: 'Я не знаю', romanization: 'Ya nye znayu', translation: "I don't know", category: 'social', isCustom: false },
];
