import type { VocabCard } from '@/lib/types';

type SeedWord = Omit<VocabCard, 'id' | 'srsLevel' | 'interval' | 'repetitions' | 'easeFactor' | 'dueDate' | 'createdAt' | 'updatedAt'>;

export const russianWords: SeedWord[] = [
  {
    languageCode: 'ru',
    word: 'и',
    romanization: 'i',
    translation: 'and',
    partOfSpeech: 'particle',
    frequency: 1,
    mnemonicStory: 'The word "и" looks like a mirror-flipped "N" — imagine two friends standing on either side, connected AND linked together.',
    exampleSentences: [{ sentence: 'Ты и я', translation: 'You and I' }],
    tags: ['core', 'conjunction'],
  },
  {
    languageCode: 'ru',
    word: 'в',
    romanization: 'v',
    translation: 'in, at, to',
    partOfSpeech: 'particle',
    frequency: 2,
    mnemonicStory: 'Shape of a "V" — think of diving INTO something, going IN deep like a V into water.',
    exampleSentences: [{ sentence: 'Я в Москве', translation: 'I am in Moscow' }],
    tags: ['core', 'preposition'],
  },
  {
    languageCode: 'ru',
    word: 'не',
    romanization: 'nye',
    translation: 'not',
    partOfSpeech: 'particle',
    frequency: 3,
    mnemonicStory: 'Sound like "Nay!" — NOT that! Imagine shaking your head and saying "Nye! NOT happening!"',
    exampleSentences: [{ sentence: 'Я не знаю', translation: 'I do not know' }],
    tags: ['core', 'negation'],
  },
  {
    languageCode: 'ru',
    word: 'он',
    romanization: 'on',
    translation: 'he',
    partOfSpeech: 'other',
    frequency: 4,
    mnemonicStory: "Sounds like \"on\" — HE is ON the move, he's the one who keeps going ON.",
    exampleSentences: [{ sentence: 'Он студент', translation: 'He is a student' }],
    tags: ['core', 'pronoun'],
  },
  {
    languageCode: 'ru',
    word: 'на',
    romanization: 'na',
    translation: 'on, at',
    partOfSpeech: 'particle',
    frequency: 5,
    mnemonicStory: 'Sounds like "na" as in "nah, put it ON there." Place something ON a surface — NA the table.',
    exampleSentences: [{ sentence: 'Книга на столе', translation: 'The book is on the table' }],
    tags: ['core', 'preposition'],
  },
  {
    languageCode: 'ru',
    word: 'я',
    romanization: 'ya',
    translation: 'I',
    partOfSpeech: 'other',
    frequency: 6,
    mnemonicStory: 'Sounds like "ya" — YA, I did it! It\'s always about ME (I), and YA confirms it proudly.',
    exampleSentences: [{ sentence: 'Я учусь', translation: 'I am studying' }],
    tags: ['core', 'pronoun'],
  },
  {
    languageCode: 'ru',
    word: 'что',
    romanization: 'shto',
    translation: 'what, that',
    partOfSpeech: 'other',
    frequency: 7,
    mnemonicStory: 'Sounds like "SHTO" — imagine a shocked "SHOOT! WHAT?!" when something surprises you.',
    exampleSentences: [{ sentence: 'Что это?', translation: 'What is this?' }],
    tags: ['core', 'question'],
  },
  {
    languageCode: 'ru',
    word: 'это',
    romanization: 'eta',
    translation: 'this, it',
    partOfSpeech: 'other',
    frequency: 8,
    mnemonicStory: 'Sounds like "eta" as in ETA (estimated time of arrival) — THIS is when it arrives. THIS is it.',
    exampleSentences: [{ sentence: 'Это моя книга', translation: 'This is my book' }],
    tags: ['core', 'demonstrative'],
  },
  {
    languageCode: 'ru',
    word: 'как',
    romanization: 'kak',
    translation: 'how, like',
    partOfSpeech: 'other',
    frequency: 9,
    mnemonicStory: 'Sounds like "cack" — HOW does a duck go? "Kak kak kak!" Like a quack showing HOW.',
    exampleSentences: [{ sentence: 'Как дела?', translation: 'How are you?' }],
    tags: ['core', 'question'],
  },
  {
    languageCode: 'ru',
    word: 'она',
    romanization: 'ana',
    translation: 'she',
    partOfSpeech: 'other',
    frequency: 10,
    mnemonicStory: 'Sounds like "Ana" — SHE is named Ana. Picture a woman named Ana whenever you hear "она."',
    exampleSentences: [{ sentence: 'Она красивая', translation: 'She is beautiful' }],
    tags: ['core', 'pronoun'],
  },
  {
    languageCode: 'ru',
    word: 'мы',
    romanization: 'my',
    translation: 'we',
    partOfSpeech: 'other',
    frequency: 11,
    mnemonicStory: 'Sounds like "my" — WE all share this, it\'s all of MY group — WE are together.',
    exampleSentences: [{ sentence: 'Мы друзья', translation: 'We are friends' }],
    tags: ['core', 'pronoun'],
  },
  {
    languageCode: 'ru',
    word: 'они',
    romanization: 'ani',
    translation: 'they',
    partOfSpeech: 'other',
    frequency: 12,
    mnemonicStory: 'Sounds like "Annie" — THEY are all Annies, a whole crowd of them over there.',
    exampleSentences: [{ sentence: 'Они говорят', translation: 'They speak' }],
    tags: ['core', 'pronoun'],
  },
  {
    languageCode: 'ru',
    word: 'ты',
    romanization: 'ty',
    translation: 'you (informal)',
    partOfSpeech: 'other',
    frequency: 13,
    mnemonicStory: 'Sounds like "tea" — Hey YOU, want some tea? Informal YOU, like a friend you offer tea to.',
    exampleSentences: [{ sentence: 'Ты молодец', translation: 'You are great' }],
    tags: ['core', 'pronoun'],
  },
  {
    languageCode: 'ru',
    word: 'вы',
    romanization: 'vy',
    translation: 'you (formal/plural)',
    partOfSpeech: 'other',
    frequency: 14,
    mnemonicStory: 'Sounds like "vy" — Very formal YOU. Use "Vy" (Very politely) for respectful situations.',
    exampleSentences: [{ sentence: 'Вы говорите по-русски?', translation: 'Do you speak Russian?' }],
    tags: ['core', 'pronoun', 'formal'],
  },
  {
    languageCode: 'ru',
    word: 'да',
    romanization: 'da',
    translation: 'yes',
    partOfSpeech: 'particle',
    frequency: 15,
    mnemonicStory: 'Sounds like "dah!" — YES! Da-da! Like a baby\'s first YES moment of discovery.',
    exampleSentences: [{ sentence: 'Да, я понимаю', translation: 'Yes, I understand' }],
    tags: ['core'],
  },
  {
    languageCode: 'ru',
    word: 'нет',
    romanization: 'nyet',
    translation: 'no, there is not',
    partOfSpeech: 'particle',
    frequency: 16,
    mnemonicStory: 'Sounds like "nyet" — a firm Russian "Nyet!" like a bouncer saying NO and blocking entry.',
    exampleSentences: [{ sentence: 'Нет, спасибо', translation: 'No, thank you' }],
    tags: ['core'],
  },
  {
    languageCode: 'ru',
    word: 'так',
    romanization: 'tak',
    translation: 'so, thus, like that',
    partOfSpeech: 'particle',
    frequency: 17,
    mnemonicStory: 'Sounds like "tack" — a thumbtack pins things down: SO that\'s the point, THUS it stays.',
    exampleSentences: [{ sentence: 'Вот так', translation: "Like this, that's how" }],
    tags: ['core'],
  },
  {
    languageCode: 'ru',
    word: 'но',
    romanization: 'no',
    translation: 'but',
    partOfSpeech: 'particle',
    frequency: 18,
    mnemonicStory: 'Sounds like "no" — BUT wait, it\'s not a negation here, it\'s a contrast: "yes, BUT..."',
    exampleSentences: [{ sentence: 'Хорошо, но дорого', translation: 'Good, but expensive' }],
    tags: ['core', 'conjunction'],
  },
  {
    languageCode: 'ru',
    word: 'если',
    romanization: 'yesli',
    translation: 'if',
    partOfSpeech: 'particle',
    frequency: 19,
    mnemonicStory: 'Sounds like "yes-lee" — "Yes... IF you say please!" Conditional: IF this, then that.',
    exampleSentences: [{ sentence: 'Если хочешь', translation: 'If you want' }],
    tags: ['core', 'conjunction'],
  },
  {
    languageCode: 'ru',
    word: 'уже',
    romanization: 'uzhe',
    translation: 'already',
    partOfSpeech: 'adv',
    frequency: 20,
    mnemonicStory: 'Sounds like "oo-zheh" — "Ooh, ZHE done it ALREADY!" past the finish line.',
    exampleSentences: [{ sentence: 'Я уже знаю', translation: 'I already know' }],
    tags: ['core'],
  },
  {
    languageCode: 'ru',
    word: 'ещё',
    romanization: 'yeshchyo',
    translation: 'still, yet, more',
    partOfSpeech: 'adv',
    frequency: 21,
    mnemonicStory: 'Sounds like "yesh-CHO!" — "Yes! MORE! STILL going!" like an energetic encore shout.',
    exampleSentences: [{ sentence: 'Ещё раз', translation: 'One more time' }],
    tags: ['core'],
  },
  {
    languageCode: 'ru',
    word: 'только',
    romanization: "tol'ka",
    translation: 'only, just',
    partOfSpeech: 'adv',
    frequency: 22,
    mnemonicStory: 'Sounds like "toll-ka" — paying a TOLL: you ONLY get through if you pay. ONLY one way.',
    exampleSentences: [{ sentence: 'Только один раз', translation: 'Only once' }],
    tags: ['core'],
  },
  {
    languageCode: 'ru',
    word: 'вот',
    romanization: 'vot',
    translation: 'here is, there is, look',
    partOfSpeech: 'particle',
    frequency: 23,
    mnemonicStory: 'Sounds like "vote" — HERE is the ballot. VOT — I present it to you right HERE.',
    exampleSentences: [{ sentence: 'Вот моя семья', translation: 'Here is my family' }],
    tags: ['core'],
  },
  {
    languageCode: 'ru',
    word: 'там',
    romanization: 'tam',
    translation: 'there',
    partOfSpeech: 'adv',
    frequency: 24,
    mnemonicStory: 'Sounds like "tam" as in "tambourine" — picture a tambourine being played over THERE, in the distance.',
    exampleSentences: [{ sentence: 'Он там', translation: 'He is there' }],
    tags: ['core'],
  },
  {
    languageCode: 'ru',
    word: 'тут',
    romanization: 'tut',
    translation: 'here',
    partOfSpeech: 'adv',
    frequency: 25,
    mnemonicStory: 'Sounds like "toot" — a horn toot RIGHT HERE, "toot toot, I\'m HERE right now!"',
    exampleSentences: [{ sentence: 'Я тут', translation: 'I am here' }],
    tags: ['core'],
  },
  {
    languageCode: 'ru',
    word: 'где',
    romanization: 'gdye',
    translation: 'where',
    partOfSpeech: 'other',
    frequency: 26,
    mnemonicStory: "Sounds like \"gdye\" — \"G-day! WHERE did everyone go?\" An Australian asking WHERE after a G'day.",
    exampleSentences: [{ sentence: 'Где ты?', translation: 'Where are you?' }],
    tags: ['core', 'question'],
  },
  {
    languageCode: 'ru',
    word: 'когда',
    romanization: 'kagda',
    translation: 'when',
    partOfSpeech: 'other',
    frequency: 27,
    mnemonicStory: "Sounds like \"cog-dah\" — a clock COG clicks DA (yes) — WHEN the cog clicks, that's WHEN.",
    exampleSentences: [{ sentence: 'Когда ты придёшь?', translation: 'When will you come?' }],
    tags: ['core', 'question'],
  },
  {
    languageCode: 'ru',
    word: 'кто',
    romanization: 'kto',
    translation: 'who',
    partOfSpeech: 'other',
    frequency: 28,
    mnemonicStory: 'Sounds like "k-to" — "K, TO whom does this belong? WHO is responsible?" K stands for WHO.',
    exampleSentences: [{ sentence: 'Кто это?', translation: 'Who is this?' }],
    tags: ['core', 'question'],
  },
  {
    languageCode: 'ru',
    word: 'говорить',
    romanization: "gavarit'",
    translation: 'to speak, to say',
    partOfSpeech: 'verb',
    frequency: 29,
    mnemonicStory: 'Sounds like "ga-va-REET" — a parrot that goes "ga-va-reet!" SPEAKS constantly all day.',
    exampleSentences: [{ sentence: 'Я говорю по-русски', translation: 'I speak Russian' }],
    tags: ['core', 'communication'],
  },
  {
    languageCode: 'ru',
    word: 'знать',
    romanization: "znat'",
    translation: 'to know',
    partOfSpeech: 'verb',
    frequency: 30,
    mnemonicStory: 'Sounds like "z-nat" — "Z-gnat" — a wise old gnat that KNOWS everything, a know-it-all bug.',
    exampleSentences: [{ sentence: 'Я не знаю', translation: "I don't know" }],
    tags: ['core'],
  },
  {
    languageCode: 'ru',
    word: 'хотеть',
    romanization: "khatyet'",
    translation: 'to want',
    partOfSpeech: 'verb',
    frequency: 31,
    mnemonicStory: 'Sounds like "hot-yet?" — Are you HOT yet? Do you WANT some water? HOT = WANT.',
    exampleSentences: [{ sentence: 'Я хочу пить', translation: 'I want to drink' }],
    tags: ['core'],
  },
  {
    languageCode: 'ru',
    word: 'можно',
    romanization: 'mozhna',
    translation: 'one can, it is allowed, may I',
    partOfSpeech: 'other',
    frequency: 32,
    mnemonicStory: 'Sounds like "mojno" — "Mo-jo-no!" Your mojo lets you. MAY I use my mojo? It\'s ALLOWED.',
    exampleSentences: [{ sentence: 'Можно мне...?', translation: 'May I have...?' }],
    tags: ['core', 'permission'],
  },
  {
    languageCode: 'ru',
    word: 'время',
    romanization: 'vremya',
    translation: 'time',
    partOfSpeech: 'noun',
    frequency: 33,
    mnemonicStory: 'Sounds like "vrem-ya" — "Vroom-ya!" TIME flies like a vroom of an engine speeding through.',
    exampleSentences: [{ sentence: 'Сколько времени?', translation: 'What time is it?' }],
    tags: ['core', 'time'],
  },
  {
    languageCode: 'ru',
    word: 'день',
    romanization: "dyen'",
    translation: 'day',
    partOfSpeech: 'noun',
    frequency: 34,
    mnemonicStory: 'Sounds like "dyen" — like "den" where a bear sleeps through the DAY. Each DEN holds a DAY.',
    exampleSentences: [{ sentence: 'Добрый день', translation: 'Good day/afternoon' }],
    tags: ['core', 'time'],
  },
  {
    languageCode: 'ru',
    word: 'год',
    romanization: 'got',
    translation: 'year',
    partOfSpeech: 'noun',
    frequency: 35,
    mnemonicStory: 'Sounds like "got" — you GOT older by one YEAR. You GOT another year of experience.',
    exampleSentences: [{ sentence: 'В этом году', translation: 'This year' }],
    tags: ['core', 'time'],
  },
  {
    languageCode: 'ru',
    word: 'человек',
    romanization: 'chelovyek',
    translation: 'person, human',
    partOfSpeech: 'noun',
    frequency: 36,
    mnemonicStory: 'Sounds like "chelo-vyek" — a "cello-vek" — a PERSON who plays cello. Every HUMAN has a unique sound.',
    exampleSentences: [{ sentence: 'Хороший человек', translation: 'A good person' }],
    tags: ['core'],
  },
  {
    languageCode: 'ru',
    word: 'большой',
    romanization: "bol'shoy",
    translation: 'big, large',
    partOfSpeech: 'adj',
    frequency: 37,
    mnemonicStory: 'Sounds like "Bolshoi" — the Bolshoi Ballet! A BIG, grand, LARGE spectacle in a massive theater.',
    exampleSentences: [{ sentence: 'Большой город', translation: 'Big city' }],
    tags: ['core', 'size'],
  },
  {
    languageCode: 'ru',
    word: 'хороший',
    romanization: 'khoroshy',
    translation: 'good, nice',
    partOfSpeech: 'adj',
    frequency: 38,
    mnemonicStory: 'Sounds like "hora-she" — "Hora-show" — a GOOD hora dance at a celebration! GOOD times.',
    exampleSentences: [{ sentence: 'Хороший день', translation: 'A good day' }],
    tags: ['core'],
  },
  {
    languageCode: 'ru',
    word: 'жизнь',
    romanization: "zhyzn'",
    translation: 'life',
    partOfSpeech: 'noun',
    frequency: 39,
    mnemonicStory: 'Sounds like "zhizn" — "VISION" of LIFE. Your vision (zhizn) IS your LIFE unfolding.',
    exampleSentences: [{ sentence: 'Жизнь прекрасна', translation: 'Life is beautiful' }],
    tags: ['core', 'philosophy'],
  },
  {
    languageCode: 'ru',
    word: 'всегда',
    romanization: 'vsegda',
    translation: 'always',
    partOfSpeech: 'adv',
    frequency: 40,
    mnemonicStory: 'Sounds like "vseg-da" — "Yes-gah-dah!" — ALWAYS say yes (da) to everything, vsegda!',
    exampleSentences: [{ sentence: 'Я всегда здесь', translation: 'I am always here' }],
    tags: ['core'],
  },
  {
    languageCode: 'ru',
    word: 'спасибо',
    romanization: 'spasiba',
    translation: 'thank you',
    partOfSpeech: 'other',
    frequency: 41,
    mnemonicStory: 'Sounds like "spa-SEE-ba" — a SPA you can SEE from afar, thanking the universe for it. THANK YOU for the spa!',
    exampleSentences: [{ sentence: 'Большое спасибо', translation: 'Thank you very much' }],
    tags: ['core', 'politeness'],
  },
  {
    languageCode: 'ru',
    word: 'пожалуйста',
    romanization: 'pazhalsta',
    translation: "please, you're welcome",
    partOfSpeech: 'other',
    frequency: 42,
    mnemonicStory: 'Sounds like "pa-zhal-sta" — "Please jal-sta" — imagine politely asking "pa-PLEASE!"',
    exampleSentences: [{ sentence: 'Дайте мне, пожалуйста', translation: 'Give me, please' }],
    tags: ['core', 'politeness'],
  },
  {
    languageCode: 'ru',
    word: 'привет',
    romanization: 'privyet',
    translation: 'hi, hello (informal)',
    partOfSpeech: 'other',
    frequency: 43,
    mnemonicStory: 'Sounds like "pre-VYET" — "pre-VET" — before going to the vet you say HI to your pet. Warm hello.',
    exampleSentences: [{ sentence: 'Привет, как дела?', translation: 'Hi, how are you?' }],
    tags: ['core', 'greetings'],
  },
  {
    languageCode: 'ru',
    word: 'здравствуйте',
    romanization: 'zdravstvuyte',
    translation: 'hello (formal)',
    partOfSpeech: 'other',
    frequency: 44,
    mnemonicStory: 'Sounds like "zdrav-stvuy-tye" — imagine a very formal gentleman tipping his hat: formal HELLO.',
    exampleSentences: [{ sentence: 'Здравствуйте, рад познакомиться', translation: 'Hello, nice to meet you' }],
    tags: ['core', 'greetings', 'formal'],
  },
  {
    languageCode: 'ru',
    word: 'понимать',
    romanization: "panimat'",
    translation: 'to understand',
    partOfSpeech: 'verb',
    frequency: 45,
    mnemonicStory: 'Sounds like "pani-MAT" — "pan-i-mat" — the PAN I MADE clicks when I UNDERSTAND the recipe.',
    exampleSentences: [{ sentence: 'Я не понимаю', translation: "I don't understand" }],
    tags: ['core', 'communication'],
  },
  {
    languageCode: 'ru',
    word: 'видеть',
    romanization: "videt'",
    translation: 'to see',
    partOfSpeech: 'verb',
    frequency: 46,
    mnemonicStory: 'Sounds like "VID-yet" — VIDEO! You SEE videos. To SEE is like watching a vid.',
    exampleSentences: [{ sentence: 'Я вижу тебя', translation: 'I see you' }],
    tags: ['core', 'senses'],
  },
  {
    languageCode: 'ru',
    word: 'идти',
    romanization: 'idti',
    translation: 'to go (on foot)',
    partOfSpeech: 'verb',
    frequency: 47,
    mnemonicStory: 'Sounds like "id-TEE" — "ID-tee" — you show your ID and GO through the gate on foot.',
    exampleSentences: [{ sentence: 'Я иду домой', translation: 'I am going home' }],
    tags: ['core', 'movement'],
  },
  {
    languageCode: 'ru',
    word: 'работа',
    romanization: 'rabota',
    translation: 'work, job',
    partOfSpeech: 'noun',
    frequency: 48,
    mnemonicStory: 'Sounds like "rah-BOT-ah" — a ROBOT does the WORK. "Rabota" is work done by a robot.',
    exampleSentences: [{ sentence: 'Где твоя работа?', translation: 'Where is your work?' }],
    tags: ['work'],
  },
  {
    languageCode: 'ru',
    word: 'дом',
    romanization: 'dom',
    translation: 'house, home',
    partOfSpeech: 'noun',
    frequency: 49,
    mnemonicStory: 'Sounds like "dome" — your HOME has a dome on top, like a grand HOME with a magnificent dome.',
    exampleSentences: [{ sentence: 'Мой дом — моя крепость', translation: 'My home is my castle' }],
    tags: ['core', 'home'],
  },
  {
    languageCode: 'ru',
    word: 'друг',
    romanization: 'druk',
    translation: 'friend',
    partOfSpeech: 'noun',
    frequency: 50,
    mnemonicStory: 'Sounds like "droog" — in A Clockwork Orange, droogs are FRIENDS (albeit dangerous ones). A FRIEND is a droog.',
    exampleSentences: [{ sentence: 'Он мой друг', translation: 'He is my friend' }],
    tags: ['core', 'relationships'],
  },
  {
    languageCode: 'ru',
    word: 'любить',
    romanization: "lyubit'",
    translation: 'to love, to like',
    partOfSpeech: 'verb',
    frequency: 51,
    mnemonicStory: 'Sounds like "lyoo-beet" — "YOU-beat" my heart — I LOVE you, you make my heart beat!',
    exampleSentences: [{ sentence: 'Я люблю тебя', translation: 'I love you' }],
    tags: ['core', 'emotions'],
  },
  {
    languageCode: 'ru',
    word: 'думать',
    romanization: "dumat'",
    translation: 'to think',
    partOfSpeech: 'verb',
    frequency: 52,
    mnemonicStory: 'Sounds like "doo-mat" — "dumb-at" — even when dumb, you THINK. To THINK is to overcome being dumb.',
    exampleSentences: [{ sentence: 'Я думаю, что...', translation: 'I think that...' }],
    tags: ['core', 'cognition'],
  },
  {
    languageCode: 'ru',
    word: 'сказать',
    romanization: "skazat'",
    translation: 'to say (perfective)',
    partOfSpeech: 'verb',
    frequency: 53,
    mnemonicStory: 'Sounds like "ska-ZAT" — a ska musician goes ZAT! and SAYS something with his trumpet.',
    exampleSentences: [{ sentence: 'Что ты хочешь сказать?', translation: 'What do you want to say?' }],
    tags: ['core', 'communication'],
  },
  {
    languageCode: 'ru',
    word: 'страна',
    romanization: 'strana',
    translation: 'country',
    partOfSpeech: 'noun',
    frequency: 54,
    mnemonicStory: 'Sounds like "stra-NA" — "STRANGE land" — every COUNTRY is a STRANGE new place to explore.',
    exampleSentences: [{ sentence: 'Какая красивая страна!', translation: 'What a beautiful country!' }],
    tags: ['geography'],
  },
  {
    languageCode: 'ru',
    word: 'рука',
    romanization: 'ruka',
    translation: 'hand, arm',
    partOfSpeech: 'noun',
    frequency: 55,
    mnemonicStory: 'Sounds like "roo-KA" — a kangaroo (roo) using its KA-powerful HAND/ARM to box.',
    exampleSentences: [{ sentence: 'Дай мне руку', translation: 'Give me your hand' }],
    tags: ['body'],
  },
  {
    languageCode: 'ru',
    word: 'слово',
    romanization: 'slova',
    translation: 'word',
    partOfSpeech: 'noun',
    frequency: 56,
    mnemonicStory: "Sounds like \"SLO-va\" — a SLOW \"va\" sound — WORDS come slowly when you're searching for them.",
    exampleSentences: [{ sentence: 'Какое слово?', translation: 'What word?' }],
    tags: ['language'],
  },
  {
    languageCode: 'ru',
    word: 'язык',
    romanization: 'yazyk',
    translation: 'language, tongue',
    partOfSpeech: 'noun',
    frequency: 57,
    mnemonicStory: 'Sounds like "ya-ZEEK" — YA SEEK a new LANGUAGE! Ya seek the tongue. LANGUAGE is what ya seek.',
    exampleSentences: [{ sentence: 'Русский язык', translation: 'Russian language' }],
    tags: ['language'],
  },
  {
    languageCode: 'ru',
    word: 'учить',
    romanization: "uchit'",
    translation: 'to learn, to teach',
    partOfSpeech: 'verb',
    frequency: 58,
    mnemonicStory: 'Sounds like "oo-CHEET" — "oo-CHEAT!" — when you LEARN the rules, you no longer need to cheat.',
    exampleSentences: [{ sentence: 'Я учу русский язык', translation: 'I am learning Russian' }],
    tags: ['language', 'education'],
  },
  {
    languageCode: 'ru',
    word: 'книга',
    romanization: 'kniga',
    translation: 'book',
    partOfSpeech: 'noun',
    frequency: 59,
    mnemonicStory: 'Sounds like "KNEE-ga" — you KNEE-gag on knowledge from a BOOK, information overload!',
    exampleSentences: [{ sentence: 'Эта книга интересная', translation: 'This book is interesting' }],
    tags: ['education'],
  },
  {
    languageCode: 'ru',
    word: 'город',
    romanization: 'gorat',
    translation: 'city, town',
    partOfSpeech: 'noun',
    frequency: 60,
    mnemonicStory: 'Sounds like "GOR-at" — a GORE city — sounds dramatic, like a dark fantasy CITY.',
    exampleSentences: [{ sentence: 'Большой город', translation: 'Big city' }],
    tags: ['geography'],
  },
  {
    languageCode: 'ru',
    word: 'вода',
    romanization: 'vada',
    translation: 'water',
    partOfSpeech: 'noun',
    frequency: 61,
    mnemonicStory: 'Sounds like "VA-da" — "VODKA comes from VODA (water)!" Vodka is water-based. VODA = WATER.',
    exampleSentences: [{ sentence: 'Дайте воды, пожалуйста', translation: 'Give me water, please' }],
    tags: ['food', 'essential'],
  },
  {
    languageCode: 'ru',
    word: 'ночь',
    romanization: "noch'",
    translation: 'night',
    partOfSpeech: 'noun',
    frequency: 62,
    mnemonicStory: 'Sounds like "noch" — "NOCHE" in Spanish is NIGHT too! "Noche/Noch" — the NIGHT is universal.',
    exampleSentences: [{ sentence: 'Доброй ночи', translation: 'Good night' }],
    tags: ['time'],
  },
  {
    languageCode: 'ru',
    word: 'слышать',
    romanization: "slyshat'",
    translation: 'to hear',
    partOfSpeech: 'verb',
    frequency: 63,
    mnemonicStory: 'Sounds like "SLEE-shat" — "SLEEP-shut" your eyes but your ears HEAR everything at night.',
    exampleSentences: [{ sentence: 'Ты слышишь меня?', translation: 'Do you hear me?' }],
    tags: ['senses'],
  },
  {
    languageCode: 'ru',
    word: 'глаз',
    romanization: 'glaz',
    translation: 'eye',
    partOfSpeech: 'noun',
    frequency: 64,
    mnemonicStory: 'Sounds like "GLAZ" — GLASS EYE! A glass eye in your head — GLAZ is EYE.',
    exampleSentences: [{ sentence: 'Красивые глаза', translation: 'Beautiful eyes' }],
    tags: ['body'],
  },
  {
    languageCode: 'ru',
    word: 'сердце',
    romanization: 'sertse',
    translation: 'heart',
    partOfSpeech: 'noun',
    frequency: 65,
    mnemonicStory: 'Sounds like "SERT-se" — a CERTAIN surge in your chest — your HEART certainly pumps!',
    exampleSentences: [{ sentence: 'Моё сердце бьётся', translation: 'My heart beats' }],
    tags: ['body', 'emotions'],
  },
  {
    languageCode: 'ru',
    word: 'мир',
    romanization: 'mir',
    translation: 'world, peace',
    partOfSpeech: 'noun',
    frequency: 66,
    mnemonicStory: 'Sounds like "MEER" — the MIR space station brought PEACE through international cooperation in the WORLD.',
    exampleSentences: [{ sentence: 'Мир во всём мире', translation: 'Peace throughout the world' }],
    tags: ['core', 'philosophy'],
  },
  {
    languageCode: 'ru',
    word: 'новый',
    romanization: 'novy',
    translation: 'new',
    partOfSpeech: 'adj',
    frequency: 67,
    mnemonicStory: 'Sounds like "NO-vy" — "NOVA" — a supernova is a NEW bright explosion in the universe. NEW = NOVA.',
    exampleSentences: [{ sentence: 'Новый год', translation: 'New Year' }],
    tags: ['core'],
  },
  {
    languageCode: 'ru',
    word: 'старый',
    romanization: 'stary',
    translation: 'old',
    partOfSpeech: 'adj',
    frequency: 68,
    mnemonicStory: 'Sounds like "STA-ry" — a STAR that\'s OLD and fading, a "starry" ancient light from long ago.',
    exampleSentences: [{ sentence: 'Старый город', translation: 'Old town' }],
    tags: ['core'],
  },
  {
    languageCode: 'ru',
    word: 'красивый',
    romanization: 'krassivy',
    translation: 'beautiful, handsome',
    partOfSpeech: 'adj',
    frequency: 69,
    mnemonicStory: 'Sounds like "kra-SEE-vy" — you SEE it and go "Kraaa!" — BEAUTIFUL sight!',
    exampleSentences: [{ sentence: 'Какой красивый закат!', translation: 'What a beautiful sunset!' }],
    tags: ['appearance'],
  },
  {
    languageCode: 'ru',
    word: 'маленький',
    romanization: 'malenky',
    translation: 'small, little',
    partOfSpeech: 'adj',
    frequency: 70,
    mnemonicStory: 'Sounds like "MAL-en-key" — a MALL with a tiny KEY. The key is so SMALL it barely opens anything.',
    exampleSentences: [{ sentence: 'Маленький ребёнок', translation: 'A little child' }],
    tags: ['size'],
  },
  {
    languageCode: 'ru',
    word: 'хлеб',
    romanization: 'khleb',
    translation: 'bread',
    partOfSpeech: 'noun',
    frequency: 71,
    mnemonicStory: 'Sounds like "KHLEB" — "LOAF" scrambled. A loaf of BREAD, heavy like "khleb" sounds.',
    exampleSentences: [{ sentence: 'Свежий хлеб', translation: 'Fresh bread' }],
    tags: ['food'],
  },
  {
    languageCode: 'ru',
    word: 'деньги',
    romanization: "den'gi",
    translation: 'money',
    partOfSpeech: 'noun',
    frequency: 72,
    mnemonicStory: "Sounds like \"DEN-gee\" — \"DENG-ey\" — like Deng Xiaoping reformed China's MONEY system. Деньги = MONEY.",
    exampleSentences: [{ sentence: 'У меня нет денег', translation: 'I have no money' }],
    tags: ['money'],
  },
  {
    languageCode: 'ru',
    word: 'сейчас',
    romanization: 'seychas',
    translation: 'now, right now',
    partOfSpeech: 'adv',
    frequency: 73,
    mnemonicStory: 'Sounds like "SAY-chas" — "SAY it NOW-chas!" Say it RIGHT NOW, the moment you\'re in.',
    exampleSentences: [{ sentence: 'Я занят сейчас', translation: 'I am busy right now' }],
    tags: ['time'],
  },
  {
    languageCode: 'ru',
    word: 'потом',
    romanization: 'patom',
    translation: 'then, after, later',
    partOfSpeech: 'adv',
    frequency: 74,
    mnemonicStory: 'Sounds like "pa-TOM" — "pa-TOM" — "pa" (father) comes THEN. Dad arrives LATER, AFTER.',
    exampleSentences: [{ sentence: 'Сначала это, потом то', translation: 'First this, then that' }],
    tags: ['time'],
  },
  {
    languageCode: 'ru',
    word: 'здесь',
    romanization: 'zdyes',
    translation: 'here',
    partOfSpeech: 'adv',
    frequency: 75,
    mnemonicStory: 'Sounds like "ZDYES" — "THIS place" — Z-THESE coordinates, HERE right at this spot.',
    exampleSentences: [{ sentence: 'Я живу здесь', translation: 'I live here' }],
    tags: ['core', 'location'],
  },
  {
    languageCode: 'ru',
    word: 'почему',
    romanization: 'pachemu',
    translation: 'why',
    partOfSpeech: 'other',
    frequency: 76,
    mnemonicStory: 'Sounds like "pa-CHE-moo" — a cow says "moo" and you ask "pa-che-MOO? WHY does the cow moo?"',
    exampleSentences: [{ sentence: 'Почему нет?', translation: 'Why not?' }],
    tags: ['core', 'question'],
  },
  {
    languageCode: 'ru',
    word: 'потому что',
    romanization: 'patamu shto',
    translation: 'because',
    partOfSpeech: 'particle',
    frequency: 77,
    mnemonicStory: 'Sounds like "pa-ta-moo-SHTO" — "BECAUSE-shto" — the answer to WHY is always BECAUSE something.',
    exampleSentences: [{ sentence: 'Потому что я хочу', translation: 'Because I want to' }],
    tags: ['core', 'conjunction'],
  },
  {
    languageCode: 'ru',
    word: 'очень',
    romanization: "ochen'",
    translation: 'very, very much',
    partOfSpeech: 'adv',
    frequency: 78,
    mnemonicStory: 'Sounds like "OH-chen" — "OH CHEN!" — OH! (surprise) + Chen (intense) = VERY intense reaction.',
    exampleSentences: [{ sentence: 'Очень хорошо', translation: 'Very good' }],
    tags: ['core', 'intensity'],
  },
  {
    languageCode: 'ru',
    word: 'немного',
    romanization: 'nemnoga',
    translation: 'a little, a bit',
    partOfSpeech: 'adv',
    frequency: 79,
    mnemonicStory: 'Sounds like "nyem-NO-ga" — "nem-NO-ga" — not NO, but not a lot either. A LITTLE bit, not much.',
    exampleSentences: [{ sentence: 'Немного воды', translation: 'A little water' }],
    tags: ['quantity'],
  },
  {
    languageCode: 'ru',
    word: 'много',
    romanization: 'mnoga',
    translation: 'many, a lot',
    partOfSpeech: 'adv',
    frequency: 80,
    mnemonicStory: 'Sounds like "MNO-ga" — "MORE-ga" — MANY more. A LOT of things, MNO-many.',
    exampleSentences: [{ sentence: 'Много людей', translation: 'Many people' }],
    tags: ['quantity'],
  },
  {
    languageCode: 'ru',
    word: 'мало',
    romanization: 'mala',
    translation: 'few, little (quantity)',
    partOfSpeech: 'adv',
    frequency: 81,
    mnemonicStory: 'Sounds like "MA-lo" — "MELLOW, LOW amount" — МАЛО is a low, mellow quantity. FEW.',
    exampleSentences: [{ sentence: 'Мало времени', translation: 'Little time' }],
    tags: ['quantity'],
  },
  {
    languageCode: 'ru',
    word: 'быстро',
    romanization: 'bystro',
    translation: 'quickly, fast',
    partOfSpeech: 'adv',
    frequency: 82,
    mnemonicStory: 'Sounds like "BIST-ro" — a BISTRO! French bistros serve food QUICKLY. Bistro = fast service = быстро!',
    exampleSentences: [{ sentence: 'Говори быстрее', translation: 'Speak faster' }],
    tags: ['speed'],
  },
  {
    languageCode: 'ru',
    word: 'медленно',
    romanization: 'medlenna',
    translation: 'slowly',
    partOfSpeech: 'adv',
    frequency: 83,
    mnemonicStory: 'Sounds like "MED-len-no" — a MEDAL goes SLOW-motion during the ceremony. SLOWLY presented.',
    exampleSentences: [{ sentence: 'Говорите медленнее', translation: 'Speak more slowly' }],
    tags: ['speed'],
  },
  {
    languageCode: 'ru',
    word: 'хорошо',
    romanization: 'kharasho',
    translation: 'good, well, okay',
    partOfSpeech: 'adv',
    frequency: 84,
    mnemonicStory: 'Sounds like "kha-ra-SHO" — "hora-SHOW!" — a GOOD show at the hora dance. GOOD! Хорошо!',
    exampleSentences: [{ sentence: 'Всё хорошо', translation: 'Everything is fine/good' }],
    tags: ['core'],
  },
  {
    languageCode: 'ru',
    word: 'плохо',
    romanization: 'plokha',
    translation: 'bad, badly, poorly',
    partOfSpeech: 'adv',
    frequency: 85,
    mnemonicStory: 'Sounds like "PLO-kha" — "PLOP-khaa!" — something PLOPS badly, makes a BAD sound. ПЛОХО.',
    exampleSentences: [{ sentence: 'Мне плохо', translation: 'I feel bad/sick' }],
    tags: ['core'],
  },
  {
    languageCode: 'ru',
    word: 'можно',
    romanization: 'mozhno',
    translation: 'one may, it is possible',
    partOfSpeech: 'other',
    frequency: 86,
    mnemonicStory: 'Sounds like "MOZH-no" — "MOJO-no" — with MOJO it IS POSSIBLE. Can I? YES, it IS POSSIBLE.',
    exampleSentences: [{ sentence: 'Можно войти?', translation: 'May I come in?' }],
    tags: ['core', 'permission'],
  },
  {
    languageCode: 'ru',
    word: 'надо',
    romanization: 'nada',
    translation: 'need to, must, necessary',
    partOfSpeech: 'other',
    frequency: 87,
    mnemonicStory: 'Sounds like "NA-da" — "NADA" backwards is ADAN. You NEED to. HAVE TO. No escape from надо!',
    exampleSentences: [{ sentence: 'Надо идти', translation: 'Need to go' }],
    tags: ['core', 'necessity'],
  },
  {
    languageCode: 'ru',
    word: 'нельзя',
    romanization: "nel'zya",
    translation: 'one cannot, it is forbidden',
    partOfSpeech: 'other',
    frequency: 88,
    mnemonicStory: "Sounds like \"nyel-ZYA\" — \"NEL-zya\" — like \"NEL\" (No) + ZAP! CANNOT do this, it's forbidden. ZAP!",
    exampleSentences: [{ sentence: 'Здесь нельзя курить', translation: 'Smoking is not allowed here' }],
    tags: ['core', 'prohibition'],
  },
  {
    languageCode: 'ru',
    word: 'утро',
    romanization: 'utra',
    translation: 'morning',
    partOfSpeech: 'noun',
    frequency: 89,
    mnemonicStory: 'Sounds like "OO-tra" — "ULTRA morning person!" — ULTRA early riser greeting the MORNING.',
    exampleSentences: [{ sentence: 'Доброе утро!', translation: 'Good morning!' }],
    tags: ['time'],
  },
  {
    languageCode: 'ru',
    word: 'вечер',
    romanization: 'vyecher',
    translation: 'evening',
    partOfSpeech: 'noun',
    frequency: 90,
    mnemonicStory: 'Sounds like "VYECH-er" — "VECHER" — EVENING sounds like it echoes off the walls at dusk.',
    exampleSentences: [{ sentence: 'Добрый вечер!', translation: 'Good evening!' }],
    tags: ['time'],
  },
  {
    languageCode: 'ru',
    word: 'завтра',
    romanization: 'zavtra',
    translation: 'tomorrow',
    partOfSpeech: 'adv',
    frequency: 91,
    mnemonicStory: "Sounds like \"ZAV-tra\" — \"SAVE-tra!\" — SAVE it for TOMORROW! Zavtra = tomorrow's savings.",
    exampleSentences: [{ sentence: 'Увидимся завтра', translation: 'See you tomorrow' }],
    tags: ['time'],
  },
  {
    languageCode: 'ru',
    word: 'вчера',
    romanization: 'fchera',
    translation: 'yesterday',
    partOfSpeech: 'adv',
    frequency: 92,
    mnemonicStory: "Sounds like \"f-CHER-a\" — \"For-CHERA!\" — YESTERDAY's old cheer. Everything's \"for yesterday.\"",
    exampleSentences: [{ sentence: 'Вчера было холодно', translation: 'Yesterday it was cold' }],
    tags: ['time'],
  },
  {
    languageCode: 'ru',
    word: 'сегодня',
    romanization: 'sevodnya',
    translation: 'today',
    partOfSpeech: 'adv',
    frequency: 93,
    mnemonicStory: 'Sounds like "se-VOD-nya" — "se-VODKA-nya" — TODAY\'s the day for vodka! Say "se-vodnya" = TODAY.',
    exampleSentences: [{ sentence: 'Сегодня хорошая погода', translation: 'Today the weather is nice' }],
    tags: ['time'],
  },
  {
    languageCode: 'ru',
    word: 'неделя',
    romanization: 'nedelya',
    translation: 'week',
    partOfSpeech: 'noun',
    frequency: 94,
    mnemonicStory: 'Sounds like "ne-DYEL-ya" — "no-DEAL-ya" — the WEEK passes with NO DEAL made. 7 days, no deal.',
    exampleSentences: [{ sentence: 'На следующей неделе', translation: 'Next week' }],
    tags: ['time'],
  },
  {
    languageCode: 'ru',
    word: 'месяц',
    romanization: 'mesyats',
    translation: 'month, moon',
    partOfSpeech: 'noun',
    frequency: 95,
    mnemonicStory: 'Sounds like "MES-yats" — "MESA-yach" — a MESA under the MOON, one MONTH\'s cycle of the moon.',
    exampleSentences: [{ sentence: 'В этом месяце', translation: 'This month' }],
    tags: ['time'],
  },
  {
    languageCode: 'ru',
    word: 'число',
    romanization: 'chislo',
    translation: 'number, date',
    partOfSpeech: 'noun',
    frequency: 96,
    mnemonicStory: 'Sounds like "CHIS-lo" — "CHISEL-lo" — you CHISEL a NUMBER into stone. The NUMBER is carved forever.',
    exampleSentences: [{ sentence: 'Какое число сегодня?', translation: "What is today's date?" }],
    tags: ['numbers', 'time'],
  },
  {
    languageCode: 'ru',
    word: 'один',
    romanization: 'odin',
    translation: 'one, alone',
    partOfSpeech: 'other',
    frequency: 97,
    mnemonicStory: 'Sounds like "o-DIN" — ODIN, the Norse god, stands ALONE on his throne — ONE king, ONE god, ALONE.',
    exampleSentences: [{ sentence: 'Один, два, три', translation: 'One, two, three' }],
    tags: ['numbers'],
  },
  {
    languageCode: 'ru',
    word: 'два',
    romanization: 'dva',
    translation: 'two',
    partOfSpeech: 'other',
    frequency: 98,
    mnemonicStory: 'Sounds like "DVA" — "TWO DVDs" — you have TWO DVAs (like the Overwatch character). TWO.',
    exampleSentences: [{ sentence: 'Нас двое', translation: 'There are two of us' }],
    tags: ['numbers'],
  },
  {
    languageCode: 'ru',
    word: 'три',
    romanization: 'tri',
    translation: 'three',
    partOfSpeech: 'other',
    frequency: 99,
    mnemonicStory: 'Sounds like "TRY" — TRY THREE times! On your third TRY (три), you succeed. THREE tries.',
    exampleSentences: [{ sentence: 'Три кофе, пожалуйста', translation: 'Three coffees, please' }],
    tags: ['numbers'],
  },
  {
    languageCode: 'ru',
    word: 'нужно',
    romanization: 'nuzhna',
    translation: 'necessary, need',
    partOfSpeech: 'other',
    frequency: 100,
    mnemonicStory: 'Sounds like "NOOZH-na" — "NOSE-na!" — you NEED your NOSE. It\'s NECESSARY! Can\'t live without it.',
    exampleSentences: [{ sentence: 'Мне нужно идти', translation: 'I need to go' }],
    tags: ['core', 'necessity'],
  },
];
